### ISSUE TITLE
API Key in fixture

### ISSUE THREAD

**Issue by jmt-gh** [leocabeza/clash_of_clans#9]
Looks like the API key is still available in the fixture at `spec/fixtures/class_cassettes/clan.yml`. You can have VCR automatically resolve this by using the `filter_sensitive_data method`. Convention is to wrap the filtered data in < and >, a la <API KEY>.

https://relishapp.com/vcr/vcr/v/3-0-1/docs/configuration/filter-sensitive-data

**Comment by jmt-gh** [comment]
temporarily resolved this in #10

**Comment by leocabeza** [comment]
Although you are right @jletizia, I believe the solution would be to implement the `filter_sensitive_data` method in the `spec/spec_helper.rb` file, instead of replacing the API_KEY in the .yml itself.

**Comment by jmt-gh** [comment]
@leocabeza, agreed. I manually removed it from the .yml to temporarily remove your API key so that it can't be used by anyone who comes across this repository.

**Comment by leocabeza** [comment]
This is related to #6, and will be closed until that is resolved.
